Next version

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -5,7 +5,7 @@ on:
   push:
 
 permissions:
-  contents: write  # Allows the workflow to create releases
+  contents: write  # Allows the workflow to create tags and releases
 
 jobs:
   build-and-release:
@@ -33,13 +33,18 @@ jobs:
       - name: Extract Version Tag
         id: get_version
         run: |
-          VERSION=$(FOUNDRY_PROFILE=ir forge script script/Info.s.sol:Version --silent --json | jq -r '.logs[0]')
+          set -e  # Exit on error
+          VERSION=$(FOUNDRY_PROFILE=ir forge script script/Info.s.sol:Version --json | grep "logs" | jq -r '.logs[0]')
+          if [ -z "$VERSION" ]; then
+            echo "Error: Version tag could not be extracted."
+            exit 1
+          fi
           echo "Extracted version: $VERSION"
           echo "version=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Check if Tag Exists
         run: |
-          git fetch --tags
+          git fetch origin --tags --no-recurse-submodules
           if git rev-parse "refs/tags/${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
             echo "Error: Tag ${{ steps.get_version.outputs.version }} already exists."
             exit 1
